site_name: Building Web Applications using SAS®
pages:
- Home: index.md
- Design: design.md
- Backend SAS: backend.md
- Frontend Web: frontend.md
- Test: testing.md
- Deploy: deploy.md
- Document: documentation.md

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - codehilite
  - fontawesome_markdown
  - toc:
      permalink: true

extra_css: ['font-awesome.css']

# Repository
repo_name: 'macropeople/sasjs'
repo_url: 'https://github.com/macropeople/sasjs'

theme:
  name: material
  logo: 'img/runningman.jpg'
  palette:
    primary: 'White'
    accent: 'Amber'
  font:
    text: 'Open Sans'
    code: 'Ubuntu Mono'
  favicon: img/runningman.jpg
  custom_dir: 'theme'
copyright: All rights reserved &copy;2020 Macro People Ltd.
