site_name: Building Web Applications using SAS®
site_url: https://sasjs.io
nav:
  - Home: index.md
  - Quickstart:
      - Services: services.md
      - React: react.md
      - Angular: angular.md
  - Design: design.md
  - Security: security.md
  - SASjs: 
      - Adapter: sasjs-adapter.md
      - CLI Tool: sasjs-cli.md
      - MacroCore: sasjs-core.md
  - Backend SAS:
      - Getting Started: backend-getstarted.md
      - SAS9: buildsas9.md
      - VIYA: buildviya.md
  - Frontend Web:
      - Get Started: frontend-getstarted.md
      - Deployment: frontend-deployment.md
      - CORS: cors.md
  - Testing: testing.md
  - Documentation: documentation.md
  - Guides:
      - images.md
      - state-management.md
      - windows.md
      - guide-sas9.md
      - guide-viya.md
      - releasing.md
      - ide.md
  - Training: 
      - resources.md
      - workshops.md
  - Apps: apps.md
  - FAQ: faq.md 

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - codehilite
  - fontawesome_markdown
  - meta
  - toc:
      permalink: true

extra_css: ["font-awesome.css"]

plugins:
    - search
    - redirects:
        redirect_maps:
            'training/resources.md': 'resources.md'
            'training/workshops.md': 'workshops.md'

# Repository
repo_name: "sasjs-docs"
repo_url: "https://github.com/sasjs/sasjs.io"
      
theme:
  name: material
  logo: "img/logo/favicon/32.svg"
  palette:
    primary: "White"
    accent: "Amber"
  font:
    text: "Open Sans"
    code: "Ubuntu Mono"
  favicon: img/logo/favicon/32.ico
  custom_dir: "theme"
  highlightjs: true
  hljs_languages:
      - SAS
      - JavaScript
      - Bash
  extra:
    social:
      - icon: fontawesome/brands/linkedin
        link: https://linkedin.com/company/sasjs
        name: SASjs on LinkedIn
copyright: All rights reserved &copy;2020 Macro People Ltd.

google_analytics: ['UA-109713029-8', 'sasjs.io']
