site_name: Building Web Applications using SAS®
pages:
  - Home: index.md
  - Quickstart:
      - Services: quickstart/services.md
      - React: quickstart/react.md
  - Design: design.md
  - Security: security.md
  - Backend SAS:
      - Getting Started: backend/getstarted.md
      - SAS9: backend/buildsas9.md
      - VIYA: backend/buildviya.md
  - Frontend Web:
      - frontend/getstarted.md
      - frontend/deployment.md
  - Testing: testing.md
  - Documentation: documentation.md
  - Guides:
      - guides/windows.md
      - guides/state.md
      - guides/viya.md
  - Training: training.md

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - codehilite
  - fontawesome_markdown
  - toc:
      permalink: true

extra_css: ["font-awesome.css"]

# Repository
repo_name: "macropeople/sasjs"
repo_url: "https://github.com/macropeople/sasjs"

theme:
  name: material
  logo: "img/runningman.jpg"
  palette:
    primary: "White"
    accent: "Amber"
  font:
    text: "Open Sans"
    code: "Ubuntu Mono"
  favicon: img/runningman.jpg
  custom_dir: "theme"
copyright: All rights reserved &copy;2020 Macro People Ltd.
